
services:
  sql-database:
    image: "mysql:latest"
    container_name: sql-database
    volumes:
      - sql-data:/var/lib/mysql/data
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD:""
  sports-wg-backemd:


