version: '3.2'
services:
  sql-database:
    image: "mysql/mysql-server:latest"
    container_name: sql-database
    command: COPY ./schema.sql /usr/local/sql-database
    volumes:
      - /usr/local/sql-database:/usr/local/mysql/
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD:''
      - MYSQL_RANDOM_ROOT_PASSWORD:no
      - MYSQL_ALLOW_EMPTY_PASSWORD:yes



